contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
baseurl = "http://markvoelker.github.io/blog_test"
title = "Technology is Fun Because It's Always Changing"
canonifyurls = true

[index]
  category = "categories"
  tag = "tags"

[params]
  sidebartitle = "Future Relics"
  sidebartagline = "Everything we work on goes obsolete someday--and that's what makes it so much fun."

[[menu.main]]
  name = "RSS"
  url = "/index.xml"

[[menu.social]]
  pre = "<i class='fa fa-twitter'></i>"
  url = "http://www.twitter.com/marktvoelker"
  identifier = "Twitter"

[[menu.social]]
  pre = "<i class='fa fa-linkedin'></i>"
  url = "http://www.linkedin.com/in/markvoelker"
  identifier = "linkedin"

[[menu.footer]]
  name = "Blog"
  url = "/posts"

[[menu.footer]]
  name = "RSS"
  url = "/index.xml"
